export class ApplicationConstants {
    public static CVBANADE_URL: string = "https://cvbanade.com/";
    public static LOGIN: string = "Login";
    public static CREATE_MY_RESUME: string = "Create My Resume";
    public static APPLY_AS_WRITER: string = "Apply As Writer";
    public static COPYRIGHT: string = "© 2023 Copyright:";
    public static ASSETS_IMG: string = "assets/images/";
    public static EXT_POSTIMG_PATH: string = "https://i.postimg.cc/"
    public static HELP: string = "Help";
    public static REGISTER_NEW_USER: string = "New User ? Click to Register";
    public static LOGIN_WITH_GOOGLE: string = "Login with Google";
    public static LOGIN_WITH_LINKEDIN: string = "Login with LinkedIn";
    public static LOGIN_WITH_OTP: string = "Login with OTP";
    public static PASSWORD_TITLECASE: string = "Password";
    public static PASSWORD: string = "password";
    public static TEXT: string = "text";
    public static ID_PSWD_INPUT: string = "pswdInput";
    public static ID_EYE_ICON: string = "eyeIcon";
    public static TYPE: string = "type";
    public static CLASS: string = "class";
    public static ICON_EYE_SLASH: string = "fa fa-eye-slash";
    public static ICON_EYE: string = "fa fa-eye";
    public static EMAIL_PHONE: string = "Email or Phone Number";
    public static CLOSE: string = "Close";
    public static HOMEPG_IMG_TITLE: string = "Unlock your Potential on Paper!";
    public static HOMEPG_IMG_SUBTITLE: string = "Give your job search the best chance of success by presenting your skills and experience in the most compelling way possible with a professionally written resume.";
    public static STARTING_AT: string = "Just at the starting price of ₹299 only.";
    public static TRY_FOR_FREE: string = "TRY FOR FREE";
}